version: 0.2

env:
  variables:
    APP_NAME: "P3-Front-End"
phases:
  install:
    runtime-versions:
      nodejs: 18.7.0
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://my-awsome-bucket-of-files --delete